name: premixer
description: "A managing app for premixer project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.33.4
  provider: ^6.1.2
  sqflite: ^2.0.0+3
  path: ^1.8.0
  mockito: ^5.0.0
  build_runner: ^2.1.4
  sqflite_common_ffi: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
